### ISSUE TITLE
Enable submenu customization for banners and product collections

### ISSUE THREAD

**Issue by micas06gua** [vtex-apps/category-menu#70]
## Expected Behavior
**Enable submenu customization for banners and product collections or an extension point for custom sub-menu according to department ID. In this customization, you must be able to render a product collection or banner component. The extension must be designed to act in the same way as a placeholder and accept banners or display products from a collection.**

## Current Behavior
**currently it is not possible to insert banners or shelf products in the submenu.**

## Possible Solution
**01. should be customized according to the department id
02. you must have the option to enable and remove on mobile.
03. you must have an option to enter the id of the product collection that will be displayed.
04. you should have the option to apply link to the banners and image label.**

**Comment by klzns** [comment]
We are currently working on it.
